spring:
  sql:
    init:
      data-locations: classpath:sql/data-dev.sql
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: testuser
    password: testpass
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    kr.co.dealmungchi: INFO
    org.springframework.data.redis: INFO