spring:
  sql:
    init:
      data-locations: classpath:sql/data-dev.sql
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    kr.co.dealmungchi: INFO
    org.springframework.data.redis: INFO