spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      repositories:
        enabled: false
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION:ap-northeast-2}
      s3:
        bucket: ${AWS_S3_BUCKET:hotdeal}

logging:
  level:
    root: INFO
    
redis:
  stream:
    key-prefix: ${REDIS_STREAM_KEY:streamHotdeals}
    partitions: ${REDIS_STREAM_PARTITIONS:1}
    consumer-group: ${REDIS_STREAM_CONSUMER_GROUP:hotdeals-batch-group}
    consumer: ${REDIS_STREAM_CONSUMER:consumer-1}
    block-timeout: ${REDIS_STREAM_BLOCK_TIMEOUT:2000}
    batch-size: ${REDIS_STREAM_BATCH_SIZE:10}
    poll-timeout: ${REDIS_STREAM_POLL_TIMEOUT:100}
    delivery-retry-count: ${REDIS_STREAM_DELIVERY_RETRY_COUNT:3}
    message-claim-min-idle-time: ${REDIS_STREAM_MESSAGE_CLAIM_MIN_IDLE_TIME:30000}
    backpressure-buffer-size: ${REDIS_STREAM_BACKPRESSURE_BUFFER_SIZE:512}

file:
  upload-dir: ${FILE_UPLOAD_DIR:/usr/local/share/data}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
          enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        hotdeal.message.processing.time: true